name: Test

on:
    push:
        branches:
            - "master"
            - "develop"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    unit:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Copy phpunit.xml
              run: cp phpunit.xml.dist phpunit.xml

            # @TODO: remove `--ignore-platform-reqs` once the `bitwasp/bitcoin` dependency is updated
            # to accept php8
            - name: Install
              run: composer update --no-interaction --no-suggest --ignore-platform-reqs

            - name: Unit tests
              run: composer test

            - name: Codecov
              run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
